# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 11:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0002_profile'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 9, 16, 11, 11, 10, 890282, tzinfo=utc))),
                ('edited_at', models.DateTimeField(default=datetime.datetime(2016, 9, 16, 11, 11, 10, 890387, tzinfo=utc))),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='reports.Department')),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.Profile')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0447\u0435\u0442',
                'verbose_name_plural': '\u041e\u0442\u0447\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('value', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_report', to='reports.Report')),
            ],
        ),
    ]
